### PR TITLE
feat: add option to return non-zero if last attempt fails

### PR DESCRIPTION
**Pull request by joscha**
This allows to pass a flag (`-f`, `--fail-on-last`) to return non-zero if the last attempt failed.

### CODE REVIEW

**Comment by tirsen** [comment]
Thanks for the pull request! I don't think this needs to be an option. Just make it the default behavior.

**Comment by joscha** [comment]
I am happy to! Will adapt the pull request. We might want to make this a
new major version though ;)

**Comment by tirsen** [comment]
Sure, bump up the version!

**Comment by joscha** [comment]
@tirsen changed the default behaviour and made it a `0.4.0`

**Comment by tirsen** [comment]
Maybe squish the commits? Then I'll merge this.

**Comment by joscha** [comment]
Sure, does github let you do it in the PR? If not I can do it manually.

**Comment by tirsen** [comment]
Nah you can do a `git rebase -i origin/master` and squish the second commit into the first. Then you gotta do a force push.

**Comment by joscha** [comment]
@tirsen I squashed it manually and pushed the change. Just FYI: I was talking about this: https://github.com/blog/2141-squash-your-commits - github let's you do squashes through the Merge button since April.

**Comment by tirsen** [comment]
Oh I didn't know that! That's really nice, thanks for pointing it out.

**Comment by tirsen** [comment]
Merged and published.

**Comment by joscha** [comment]
Thank you!

**Pull request merged**
